AllCops:
  Exclude:
    - 'db/**/*'

# Layout
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Max: 50
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30

# Style
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MixinUsage:
  Enabled: false
