# Style
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MixinUsage:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Max: 50
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
